### ISSUE TITLE
Pycairo for graph drawing

### ISSUE THREAD

**Issue by jinsolp** [sunhongmin225/problem-solved#24]
저는 @donny-son 님이 올려주신 `make build-env` 에서 `pycairo` wheel build 가 fail 이 떴었는데요...!
mac user 분들은 `make build-env` 전에 `brew install cairo` 를 하면 실행이 잘 됩니다!! : )

**Comment by sunhongmin225** [comment]
알려주셔서 감사합니다!

**Comment by donny-son** [comment]
수정했습니다.
